{% set version = "9g" %}

package:
  name: jpeg
  version: {{ version }}

source:
  url: http://www.ijg.org/files/jpegsrc.v{{ version }}.tar.gz
  sha256: 6e004d72f9108014caccf434095514c139478c72b6b1873a3e3807ea5bec5c59
  patches:
    - CMakeLists.txt.patch  # [win]

build:
  number: 0
  run_exports:
    # compatible within major version numbers
    # https://abi-laboratory.pro/tracker/timeline/libjpeg/
    - {{ pin_subpackage('jpeg') }}

requirements:
  build:
    - cmake  # [win]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  run_constrained:
    - libjpeg-turbo <0.0.0a

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.ijg.org/
  license: IJG
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: read/write jpeg COM, EXIF, IPTC medata

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
    - jakirkham
    - msarahan
