{% set version = "8d" %}

package:
  name: jpeg
  version: {{ version }}

source:
  url: http://www.ijg.org/files/jpegsrc.v{{ version }}.tar.gz
  sha256:  00029b1473f0f0ea72fbca3230e8cb25797fbb27e58ae2e46bb8bf5a806fe0b3
  patches:
    - CMakeLists.txt.patch  # [win]
    # Update the configuration using jpeg-9c configuration files
    # also adds a libjpeg.pc file
    - patches/config_guess_8d_to_9c.patch
    - patches/config_sub_8d_to_9c.patch
    - patches/configure_ac_8d_to_9c.patch
    - patches/libjpeg.pc.in.patch

build:
  number: 0
  run_exports:
    # compatible within major version numbers
    # https://abi-laboratory.pro/tracker/timeline/libjpeg/
    - {{ pin_subpackage('jpeg') }}

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - make
    - autoconf  # [unix]

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.ijg.org/
  license: IJG
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: read/write jpeg COM, EXIF, IPTC medata

extra:
  recipe-maintainers:
    - ocefpaf
    - gillins
    - jakirkham
    - msarahan
